// ============================================================================
// B2B INDIA — DEFAULT CATEGORY FEES CONSTANTS (Client & Server Safe)
// ============================================================================

export const DEFAULT_CATEGORY_FEES = {
  'food-agriculture': 3.0,
  'industrial-machinery': 5.0,
  'building-construction': 3.0,
  'electronics-electrical': 4.0,
  'apparel-garments': 4.5,
  'chemicals-dyes': 3.5,
  'medical-healthcare': 4.0,
  'furniture-interiors': 5.0,
  'packaging-paper': 3.0,
  'automobile-parts': 4.0,
  'solar-renewable': 3.5,
  'pipes-fittings': 3.0,
  'safety-security': 4.0,
  'textiles-fabrics': 3.5,
  'pharma-drugs': 3.5,
  'rubber-products': 3.5,
  'plastic-products': 3.5,
  'gems-jewellery': 2.0,
  'printing-stationery': 3.0,
  'oil-gas': 2.5,
  'metals-steel': 2.5,
  'water-treatment': 4.0,
  'hvac-refrigeration': 4.5,
  'lab-instruments': 5.0,
  'leather-products': 4.0,
  'sports-fitness': 4.5,
  'gifts-handicrafts': 5.0,
  'telecom-equipment': 4.0,
  'mining-minerals': 2.5,
  'timber-wood': 3.5,
  'power-generation': 3.0,
  'ayurvedic-herbal': 3.5,
  'glass-ceramics': 3.5,
  'logistics-handling': 3.0,
  'marine-ship': 4.0,
  'waste-recycling': 3.0,
  'cosmetics-personal': 4.5,
  'education-training': 4.0,
};
