/**
 * B2B India Mandi Rates & Market Intelligence Service
 * Sourced from CommodityOnline & APMC Mandi Network across India
 * Powered by Google Gemini AI Analysis
 */

export const COMMODITY_ONLINE_DATA = [
  {
    id: 'turmeric',
    name: 'Turmeric (Haldi)',
    slug: 'turmeric',
    category: 'Spices & Herbs',
    sourceUrl: 'https://www.commodityonline.com/mandiprices/turmeric',
    sourceAttribution: 'CommodityOnline & APMC Agmarknet',
    primaryMarket: 'Nizamabad APMC',
    primaryState: 'Telangana',
    nationalModalPrice: 14650, // ₹ per Quintal
    nationalPricePerKg: 146.50,
    unit: 'per Quintal',
    change: 1.8,
    trend: 'up',
    volume: '2,850 MT',
    grade: 'Salem / Nizamabad Double Polished Finger',
    lastUpdated: new Date().toISOString(),
    marketSummary: 'Strong domestic stockist buying and firm export inquiries for European and Gulf destinations. Arrivals steady at Nizamabad and Sangli mandis.',
    mandis: [
      { market: 'Nizamabad', state: 'Telangana', variety: 'Finger (Double Polish)', minPrice: 13800, maxPrice: 15400, modalPrice: 14700, pricePerKg: 147.00, change: 2.1, trend: 'up', arrivals: '1,200 MT' },
      { market: 'Sangli', state: 'Maharashtra', variety: 'Rajapuri Bold', minPrice: 14500, maxPrice: 16800, modalPrice: 15800, pricePerKg: 158.00, change: 1.5, trend: 'up', arrivals: '650 MT' },
      { market: 'Erode', state: 'Tamil Nadu', variety: 'Erode Salem Finger', minPrice: 13600, maxPrice: 15100, modalPrice: 14450, pricePerKg: 144.50, change: 0.9, trend: 'up', arrivals: '580 MT' },
      { market: 'Kesamudram', state: 'Telangana', variety: 'Local Finger', minPrice: 13200, maxPrice: 14600, modalPrice: 13950, pricePerKg: 139.50, change: -0.4, trend: 'down', arrivals: '240 MT' },
      { market: 'Duggirala', state: 'Andhra Pradesh', variety: 'Guntur Medium', minPrice: 13400, maxPrice: 14800, modalPrice: 14100, pricePerKg: 141.00, change: 1.2, trend: 'up', arrivals: '180 MT' },
    ],
  },
  {
    id: 'red-chilli',
    name: 'Red Chilli (Mirchi)',
    slug: 'red-chilli',
    category: 'Spices & Herbs',
    sourceUrl: 'https://www.commodityonline.com/mandiprices/red-chilli',
    sourceAttribution: 'CommodityOnline & APMC Agmarknet',
    primaryMarket: 'Guntur APMC',
    primaryState: 'Andhra Pradesh',
    nationalModalPrice: 18400,
    nationalPricePerKg: 184.00,
    unit: 'per Quintal',
    change: 2.4,
    trend: 'up',
    volume: '4,600 MT',
    grade: 'Teja S17 Stemless',
    lastUpdated: new Date().toISOString(),
    marketSummary: 'High export demand from China, Sri Lanka, and Bangladesh. Cold storage stock release running smoothly.',
    mandis: [
      { market: 'Guntur', state: 'Andhra Pradesh', variety: 'Teja S17', minPrice: 17800, maxPrice: 19800, modalPrice: 18800, pricePerKg: 188.00, change: 2.8, trend: 'up', arrivals: '2,900 MT' },
      { market: 'Khammam', state: 'Telangana', variety: 'Teja Fatki', minPrice: 16500, maxPrice: 18200, modalPrice: 17400, pricePerKg: 174.00, change: 1.9, trend: 'up', arrivals: '850 MT' },
      { market: 'Byadgi', state: 'Karnataka', variety: 'Byadgi Kaddi', minPrice: 28000, maxPrice: 34500, modalPrice: 31200, pricePerKg: 312.00, change: 3.1, trend: 'up', arrivals: '480 MT' },
      { market: 'Warangal', state: 'Telangana', variety: 'Wonder Hot', minPrice: 17200, maxPrice: 19000, modalPrice: 18100, pricePerKg: 181.00, change: 1.1, trend: 'up', arrivals: '370 MT' },
    ],
  },
  {
    id: 'cumin-seeds',
    name: 'Cumin Seeds (Jeera)',
    slug: 'cumin-seeds',
    category: 'Spices & Herbs',
    sourceUrl: 'https://www.commodityonline.com/mandiprices/cumin-seed',
    sourceAttribution: 'CommodityOnline & APMC Agmarknet',
    primaryMarket: 'Unjha APMC',
    primaryState: 'Gujarat',
    nationalModalPrice: 28600,
    nationalPricePerKg: 286.00,
    unit: 'per Quintal',
    change: 3.2,
    trend: 'up',
    volume: '1,750 MT',
    grade: 'Machine Clean 99% Purity',
    lastUpdated: new Date().toISOString(),
    marketSummary: 'Bullish momentum supported by strong Ramadan and festive export demand. Local mandi arrivals under control.',
    mandis: [
      { market: 'Unjha', state: 'Gujarat', variety: 'Singapore 99%', minPrice: 27500, maxPrice: 30200, modalPrice: 28900, pricePerKg: 289.00, change: 3.5, trend: 'up', arrivals: '1,100 MT' },
      { market: 'Rajkot', state: 'Gujarat', variety: 'Europe Quality', minPrice: 26800, maxPrice: 29400, modalPrice: 28200, pricePerKg: 282.00, change: 2.8, trend: 'up', arrivals: '380 MT' },
      { market: 'Jodhpur', state: 'Rajasthan', variety: 'Bold Cleaned', minPrice: 26200, maxPrice: 28800, modalPrice: 27500, pricePerKg: 275.00, change: 2.1, trend: 'up', arrivals: '270 MT' },
    ],
  },
  {
    id: 'coriander-seeds',
    name: 'Coriander Seeds (Dhaniya)',
    slug: 'coriander-seeds',
    category: 'Spices & Herbs',
    sourceUrl: 'https://www.commodityonline.com/mandiprices/coriander',
    sourceAttribution: 'CommodityOnline & APMC Agmarknet',
    primaryMarket: 'Kota APMC',
    primaryState: 'Rajasthan',
    nationalModalPrice: 7750,
    nationalPricePerKg: 77.50,
    unit: 'per Quintal',
    change: -1.2,
    trend: 'down',
    volume: '1,420 MT',
    grade: 'Eagle Clean Green',
    lastUpdated: new Date().toISOString(),
    marketSummary: 'Market steady with mild profit booking. Industrial spice grinders procuring on dip.',
    mandis: [
      { market: 'Kota', state: 'Rajasthan', variety: 'Eagle Quality', minPrice: 7400, maxPrice: 8150, modalPrice: 7850, pricePerKg: 78.50, change: -1.0, trend: 'down', arrivals: '750 MT' },
      { market: 'Ramganj Mandi', state: 'Rajasthan', variety: 'Badami Green', minPrice: 7200, maxPrice: 7900, modalPrice: 7600, pricePerKg: 76.00, change: -1.5, trend: 'down', arrivals: '480 MT' },
      { market: 'Guna', state: 'Madhya Pradesh', variety: 'Scooter Grade', minPrice: 7350, maxPrice: 8050, modalPrice: 7700, pricePerKg: 77.00, change: -0.8, trend: 'down', arrivals: '190 MT' },
    ],
  },
  {
    id: 'soyabean',
    name: 'Soyabean (Yellow)',
    slug: 'soyabean',
    category: 'Pulses & Oilseeds',
    sourceUrl: 'https://www.commodityonline.com/mandiprices/soyabean',
    sourceAttribution: 'CommodityOnline & APMC Agmarknet',
    primaryMarket: 'Indore Mandi',
    primaryState: 'Madhya Pradesh',
    nationalModalPrice: 4720,
    nationalPricePerKg: 47.20,
    unit: 'per Quintal',
    change: -0.6,
    trend: 'down',
    volume: '6,400 MT',
    grade: 'Yellow FAQ (10% Moisture)',
    lastUpdated: new Date().toISOString(),
    marketSummary: 'Soymeal crushing demand steady. Global palm oil movement influencing solvent extraction plant bids.',
    mandis: [
      { market: 'Indore', state: 'Madhya Pradesh', variety: 'Yellow Milling', minPrice: 4550, maxPrice: 4880, modalPrice: 4750, pricePerKg: 47.50, change: -0.5, trend: 'down', arrivals: '2,800 MT' },
      { market: 'Latur', state: 'Maharashtra', variety: 'Yellow FAQ', minPrice: 4500, maxPrice: 4820, modalPrice: 4680, pricePerKg: 46.80, change: -0.8, trend: 'down', arrivals: '2,100 MT' },
      { market: 'Ujjain', state: 'Madhya Pradesh', variety: 'Standard Bold', minPrice: 4520, maxPrice: 4850, modalPrice: 4700, pricePerKg: 47.00, change: -0.4, trend: 'down', arrivals: '950 MT' },
      { market: 'Kota', state: 'Rajasthan', variety: 'Yellow Machine Clean', minPrice: 4580, maxPrice: 4890, modalPrice: 4740, pricePerKg: 47.40, change: -0.3, trend: 'down', arrivals: '550 MT' },
    ],
  },
  {
    id: 'black-pepper',
    name: 'Black Pepper (Kali Mirch)',
    slug: 'black-pepper',
    category: 'Spices & Herbs',
    sourceUrl: 'https://www.commodityonline.com/mandiprices/black-pepper',
    sourceAttribution: 'CommodityOnline & APMC Agmarknet',
    primaryMarket: 'Kochi Terminal',
    primaryState: 'Kerala',
    nationalModalPrice: 61500,
    nationalPricePerKg: 615.00,
    unit: 'per Quintal',
    change: 4.2,
    trend: 'up',
    volume: '510 MT',
    grade: 'MG-1 Garbled Bold',
    lastUpdated: new Date().toISOString(),
    marketSummary: 'Tight domestic supply and elevated import parity prices keep spot prices strong in Kerala and Karnataka.',
    mandis: [
      { market: 'Kochi', state: 'Kerala', variety: 'Garbled MG-1', minPrice: 59000, maxPrice: 63500, modalPrice: 62000, pricePerKg: 620.00, change: 4.5, trend: 'up', arrivals: '320 MT' },
      { market: 'Wayanad', state: 'Kerala', variety: 'Ungarbled Grade', minPrice: 57500, maxPrice: 61500, modalPrice: 60500, pricePerKg: 605.00, change: 3.9, trend: 'up', arrivals: '190 MT' },
    ],
  },
  {
    id: 'green-cardamom',
    name: 'Green Cardamom (Chhoti Elaichi)',
    slug: 'green-cardamom',
    category: 'Spices & Herbs',
    sourceUrl: 'https://www.commodityonline.com/mandiprices/cardamom',
    sourceAttribution: 'CommodityOnline & Spices Board E-Auction',
    primaryMarket: 'Vandanmedu Auction',
    primaryState: 'Kerala',
    nationalModalPrice: 248000,
    nationalPricePerKg: 2480.00,
    unit: 'per Quintal',
    change: 5.4,
    trend: 'up',
    volume: '165 MT',
    grade: '8mm+ Extra Bold',
    lastUpdated: new Date().toISOString(),
    marketSummary: 'Robust auction demand from North Indian confectioners and Gulf exporters. Grade 8mm lots receiving premium bids.',
    mandis: [
      { market: 'Vandanmedu', state: 'Kerala', variety: '8mm Extra Bold', minPrice: 235000, maxPrice: 265000, modalPrice: 252000, pricePerKg: 2520.00, change: 5.8, trend: 'up', arrivals: '95 MT' },
      { market: 'Bodinayakanur', state: 'Tamil Nadu', variety: '7-8mm Bold', minPrice: 228000, maxPrice: 252000, modalPrice: 242000, pricePerKg: 2420.00, change: 4.9, trend: 'up', arrivals: '70 MT' },
    ],
  },
  {
    id: 'mustard-seeds',
    name: 'Mustard Seeds (Sarson)',
    slug: 'mustard-seeds',
    category: 'Pulses & Oilseeds',
    sourceUrl: 'https://www.commodityonline.com/mandiprices/mustard-seed',
    sourceAttribution: 'CommodityOnline & APMC Agmarknet',
    primaryMarket: 'Jaipur Mandi',
    primaryState: 'Rajasthan',
    nationalModalPrice: 5880,
    nationalPricePerKg: 58.80,
    unit: 'per Quintal',
    change: 1.2,
    trend: 'up',
    volume: '3,100 MT',
    grade: 'Black 42% Oil Condition',
    lastUpdated: new Date().toISOString(),
    marketSummary: 'Kacchi Ghani mustard oil mills maintaining active buying support. Daily arrivals absorbing smoothly.',
    mandis: [
      { market: 'Jaipur', state: 'Rajasthan', variety: 'Condition 42%', minPrice: 5680, maxPrice: 6080, modalPrice: 5920, pricePerKg: 59.20, change: 1.4, trend: 'up', arrivals: '1,500 MT' },
      { market: 'Bharatpur', state: 'Rajasthan', variety: 'Standard Black', minPrice: 5620, maxPrice: 6000, modalPrice: 5840, pricePerKg: 58.40, change: 1.1, trend: 'up', arrivals: '920 MT' },
      { market: 'Alwar', state: 'Rajasthan', variety: 'FAQ Quality', minPrice: 5640, maxPrice: 6020, modalPrice: 5860, pricePerKg: 58.60, change: 1.0, trend: 'up', arrivals: '680 MT' },
    ],
  },
  {
    id: 'wheat',
    name: 'Wheat (Gehun)',
    slug: 'wheat',
    category: 'Grains & Cereals',
    sourceUrl: 'https://www.commodityonline.com/mandiprices/wheat',
    sourceAttribution: 'CommodityOnline & APMC Agmarknet',
    primaryMarket: 'Sehore Mandi',
    primaryState: 'Madhya Pradesh',
    nationalModalPrice: 3880,
    nationalPricePerKg: 38.80,
    unit: 'per Quintal',
    change: 0.5,
    trend: 'up',
    volume: '4,800 MT',
    grade: 'Sharbati Gold Milling',
    lastUpdated: new Date().toISOString(),
    marketSummary: 'Flour millers actively accumulating high-protein Sharbati varieties. Open market supplies tightly held.',
    mandis: [
      { market: 'Sehore', state: 'Madhya Pradesh', variety: 'Sharbati Gold', minPrice: 3650, maxPrice: 4200, modalPrice: 3950, pricePerKg: 39.50, change: 0.6, trend: 'up', arrivals: '2,200 MT' },
      { market: 'Indore', state: 'Madhya Pradesh', variety: 'Mill Quality', minPrice: 3450, maxPrice: 3850, modalPrice: 3680, pricePerKg: 36.80, change: 0.3, trend: 'up', arrivals: '1,600 MT' },
      { market: 'Khanna', state: 'Punjab', variety: 'Standard PB-343', minPrice: 3400, maxPrice: 3780, modalPrice: 3620, pricePerKg: 36.20, change: 0.4, trend: 'up', arrivals: '1,000 MT' },
    ],
  },
  {
    id: 'onions',
    name: 'Onions (Pyaz)',
    slug: 'onions',
    category: 'Vegetables & Fruits',
    sourceUrl: 'https://www.commodityonline.com/mandiprices/onion',
    sourceAttribution: 'CommodityOnline & APMC Agmarknet',
    primaryMarket: 'Lasalgaon APMC',
    primaryState: 'Maharashtra',
    nationalModalPrice: 2480,
    nationalPricePerKg: 24.80,
    unit: 'per Quintal',
    change: 2.5,
    trend: 'up',
    volume: '3,800 MT',
    grade: 'Nashik Red Export Grade',
    lastUpdated: new Date().toISOString(),
    marketSummary: 'Export dispatches to Middle East and Southeast Asia gaining pace. Lasalgaon arrivals auctioning briskly.',
    mandis: [
      { market: 'Lasalgaon', state: 'Maharashtra', variety: 'Nashik Red', minPrice: 2250, maxPrice: 2720, modalPrice: 2520, pricePerKg: 25.20, change: 2.8, trend: 'up', arrivals: '2,100 MT' },
      { market: 'Pimpalgaon', state: 'Maharashtra', variety: 'Medium Red', minPrice: 2180, maxPrice: 2650, modalPrice: 2450, pricePerKg: 24.50, change: 2.3, trend: 'up', arrivals: '1,200 MT' },
      { market: 'Pune', state: 'Maharashtra', variety: 'Local Red', minPrice: 2100, maxPrice: 2580, modalPrice: 2380, pricePerKg: 23.80, change: 1.9, trend: 'up', arrivals: '500 MT' },
    ],
  },
  {
    id: 'garlic',
    name: 'Garlic (Lahsun)',
    slug: 'garlic',
    category: 'Vegetables & Fruits',
    sourceUrl: 'https://www.commodityonline.com/mandiprices/garlic',
    sourceAttribution: 'CommodityOnline & APMC Agmarknet',
    primaryMarket: 'Neemuch Mandi',
    primaryState: 'Madhya Pradesh',
    nationalModalPrice: 16800,
    nationalPricePerKg: 168.00,
    unit: 'per Quintal',
    change: -1.8,
    trend: 'down',
    volume: '1,100 MT',
    grade: 'Ooty / Mandsaur Special Bold (45mm+)',
    lastUpdated: new Date().toISOString(),
    marketSummary: 'Fresh crop arrivals picking up in Malwa region. Processors procuring for dehydrated garlic flakes and powder.',
    mandis: [
      { market: 'Neemuch', state: 'Madhya Pradesh', variety: 'Special Bold 45mm+', minPrice: 15500, maxPrice: 18200, modalPrice: 17100, pricePerKg: 171.00, change: -1.7, trend: 'down', arrivals: '620 MT' },
      { market: 'Mandsaur', state: 'Madhya Pradesh', variety: 'Medium Desi', minPrice: 14800, maxPrice: 17400, modalPrice: 16400, pricePerKg: 164.00, change: -2.0, trend: 'down', arrivals: '350 MT' },
      { market: 'Kota', state: 'Rajasthan', variety: 'Local Bold', minPrice: 15000, maxPrice: 17600, modalPrice: 16500, pricePerKg: 165.00, change: -1.4, trend: 'down', arrivals: '130 MT' },
    ],
  },
  {
    id: 'cotton',
    name: 'Cotton (Kapas)',
    slug: 'cotton',
    category: 'Commercial Crops',
    sourceUrl: 'https://www.commodityonline.com/mandiprices/cotton',
    sourceAttribution: 'CommodityOnline & APMC Agmarknet',
    primaryMarket: 'Rajkot Mandi',
    primaryState: 'Gujarat',
    nationalModalPrice: 57400,
    nationalPricePerKg: 161.23,
    unit: 'per Candy (356kg)',
    change: 1.1,
    trend: 'up',
    volume: '2,200 Bales',
    grade: 'Shankar-6 (29mm Micronaire 3.8)',
    lastUpdated: new Date().toISOString(),
    marketSummary: 'Textile spinning mills reporting consistent yarn bookings. CCI procurement keeping benchmark floor supported.',
    mandis: [
      { market: 'Rajkot', state: 'Gujarat', variety: 'Shankar-6 29mm', minPrice: 56200, maxPrice: 58800, modalPrice: 57600, pricePerKg: 161.79, change: 1.2, trend: 'up', arrivals: '1,200 Bales' },
      { market: 'Kadi', state: 'Gujarat', variety: 'Ginning Quality', minPrice: 55800, maxPrice: 58400, modalPrice: 57200, pricePerKg: 160.67, change: 0.9, trend: 'up', arrivals: '650 Bales' },
      { market: 'Adilabad', state: 'Telangana', variety: 'Bunny / Brahma', minPrice: 55500, maxPrice: 58000, modalPrice: 56900, pricePerKg: 159.83, change: 1.0, trend: 'up', arrivals: '350 Bales' },
    ],
  },
  {
    id: 'chana',
    name: 'Chickpeas / Chana (Desi)',
    slug: 'chana',
    category: 'Pulses & Oilseeds',
    sourceUrl: 'https://www.commodityonline.com/mandiprices/gram-chana',
    sourceAttribution: 'CommodityOnline & APMC Agmarknet',
    primaryMarket: 'Bikaner APMC',
    primaryState: 'Rajasthan',
    nationalModalPrice: 6320,
    nationalPricePerKg: 63.20,
    unit: 'per Quintal',
    change: 1.9,
    trend: 'up',
    volume: '2,400 MT',
    grade: 'Cleaned Desi FAQ',
    lastUpdated: new Date().toISOString(),
    marketSummary: 'Besan manufacturing mills active. Government buffer stock holding maintains steady price equilibrium.',
    mandis: [
      { market: 'Bikaner', state: 'Rajasthan', variety: 'Desi Bold', minPrice: 6150, maxPrice: 6550, modalPrice: 6380, pricePerKg: 63.80, change: 2.1, trend: 'up', arrivals: '1,200 MT' },
      { market: 'Latur', state: 'Maharashtra', variety: 'Annagiri Chana', minPrice: 6050, maxPrice: 6420, modalPrice: 6260, pricePerKg: 62.60, change: 1.6, trend: 'up', arrivals: '780 MT' },
      { market: 'Akola', state: 'Maharashtra', variety: 'Desi Standard', minPrice: 6100, maxPrice: 6460, modalPrice: 6290, pricePerKg: 62.90, change: 1.8, trend: 'up', arrivals: '420 MT' },
    ],
  },
  {
    id: 'basmati-rice',
    name: 'Basmati Rice (1121 Pusa)',
    slug: 'basmati-rice',
    category: 'Grains & Cereals',
    sourceUrl: 'https://www.commodityonline.com/mandiprices/paddy-basmati',
    sourceAttribution: 'CommodityOnline & APMC Agmarknet',
    primaryMarket: 'Taraori Mandi',
    primaryState: 'Haryana',
    nationalModalPrice: 9350,
    nationalPricePerKg: 93.50,
    unit: 'per Quintal',
    change: -0.9,
    trend: 'down',
    volume: '3,600 MT',
    grade: 'XXL Grain (8.4mm Steam)',
    lastUpdated: new Date().toISOString(),
    marketSummary: 'Export shipments through Mundra and Kandla ports active. Rice millers buying aged paddy on requirements.',
    mandis: [
      { market: 'Taraori', state: 'Haryana', variety: '1121 Raw / Steam', minPrice: 9050, maxPrice: 9650, modalPrice: 9400, pricePerKg: 94.00, change: -0.8, trend: 'down', arrivals: '1,800 MT' },
      { market: 'Karnal', state: 'Haryana', variety: '1509 Basmati', minPrice: 8600, maxPrice: 9200, modalPrice: 8950, pricePerKg: 89.50, change: -1.1, trend: 'down', arrivals: '1,100 MT' },
      { market: 'Amritsar', state: 'Punjab', variety: 'Pusa Basmati Traditional', minPrice: 9100, maxPrice: 9700, modalPrice: 9450, pricePerKg: 94.50, change: -0.7, trend: 'down', arrivals: '700 MT' },
    ],
  },
  {
    id: 'groundnut',
    name: 'Groundnut (Moongphali)',
    slug: 'groundnut',
    category: 'Pulses & Oilseeds',
    sourceUrl: 'https://www.commodityonline.com/mandiprices/groundnut',
    sourceAttribution: 'CommodityOnline & APMC Agmarknet',
    primaryMarket: 'Rajkot Mandi',
    primaryState: 'Gujarat',
    nationalModalPrice: 6850,
    nationalPricePerKg: 68.50,
    unit: 'per Quintal',
    change: 1.4,
    trend: 'up',
    volume: '2,900 MT',
    grade: 'Bold Java 50/60 Count',
    lastUpdated: new Date().toISOString(),
    marketSummary: 'Peanut butter manufacturers and HPS exporters sourcing bold kernels at steady premium.',
    mandis: [
      { market: 'Rajkot', state: 'Gujarat', variety: 'Java Bold 50/60', minPrice: 6600, maxPrice: 7150, modalPrice: 6920, pricePerKg: 69.20, change: 1.6, trend: 'up', arrivals: '1,500 MT' },
      { market: 'Gondal', state: 'Gujarat', variety: 'TJ 80/90', minPrice: 6450, maxPrice: 6980, modalPrice: 6780, pricePerKg: 67.80, change: 1.2, trend: 'up', arrivals: '950 MT' },
      { market: 'Junagadh', state: 'Gujarat', variety: 'Western Bold', minPrice: 6500, maxPrice: 7050, modalPrice: 6840, pricePerKg: 68.40, change: 1.3, trend: 'up', arrivals: '450 MT' },
    ],
  },
  {
    id: 'maize',
    name: 'Maize / Corn (Makka)',
    slug: 'maize',
    category: 'Grains & Cereals',
    sourceUrl: 'https://www.commodityonline.com/mandiprices/maize',
    sourceAttribution: 'CommodityOnline & APMC Agmarknet',
    primaryMarket: 'Chhindwara Mandi',
    primaryState: 'Madhya Pradesh',
    nationalModalPrice: 2320,
    nationalPricePerKg: 23.20,
    unit: 'per Quintal',
    change: 0.8,
    trend: 'up',
    volume: '4,100 MT',
    grade: 'Yellow Feed / Starch Grade',
    lastUpdated: new Date().toISOString(),
    marketSummary: 'Ethanol distilleries and poultry feed manufacturers providing continuous buying support.',
    mandis: [
      { market: 'Chhindwara', state: 'Madhya Pradesh', variety: 'Yellow Starch', minPrice: 2200, maxPrice: 2450, modalPrice: 2350, pricePerKg: 23.50, change: 0.9, trend: 'up', arrivals: '2,200 MT' },
      { market: 'Davangere', state: 'Karnataka', variety: 'Feed Grade', minPrice: 2180, maxPrice: 2420, modalPrice: 2310, pricePerKg: 23.10, change: 0.7, trend: 'up', arrivals: '1,400 MT' },
      { market: 'Gulabbagh', state: 'Bihar', variety: 'Purnea Yellow', minPrice: 2150, maxPrice: 2380, modalPrice: 2280, pricePerKg: 22.80, change: 0.6, trend: 'up', arrivals: '500 MT' },
    ],
  },
];

/**
 * Normalizes user queries to matched commodity
 */
export function findCommodityByQuery(query) {
  if (!query) return null;
  const q = query.toLowerCase().trim();

  // Direct matches
  for (const item of COMMODITY_ONLINE_DATA) {
    if (item.id === q || item.slug === q) return item;
    if (item.name.toLowerCase().includes(q)) return item;
  }

  // Common synonym map
  const synonyms = {
    'haldi': 'turmeric',
    'turmeric finger': 'turmeric',
    'mirch': 'red-chilli',
    'mirchi': 'red-chilli',
    'chilli': 'red-chilli',
    'jeera': 'cumin-seeds',
    'cumin': 'cumin-seeds',
    'dhaniya': 'coriander-seeds',
    'coriander': 'coriander-seeds',
    'soya': 'soyabean',
    'soyabean seed': 'soyabean',
    'pepper': 'black-pepper',
    'kali mirch': 'black-pepper',
    'elaichi': 'green-cardamom',
    'cardamom': 'green-cardamom',
    'sarson': 'mustard-seeds',
    'mustard': 'mustard-seeds',
    'gehun': 'wheat',
    'pyaz': 'onions',
    'onion': 'onions',
    'lahsun': 'garlic',
    'garlic': 'garlic',
    'kapas': 'cotton',
    'chickpeas': 'chana',
    'chickpea': 'chana',
    'gram': 'chana',
    'rice': 'basmati-rice',
    'paddy': 'basmati-rice',
    'moongphali': 'groundnut',
    'peanut': 'groundnut',
    'corn': 'maize',
    'makka': 'maize',
  };

  for (const [syn, targetId] of Object.entries(synonyms)) {
    if (q.includes(syn)) {
      return COMMODITY_ONLINE_DATA.find((c) => c.id === targetId) || null;
    }
  }

  return null;
}

/**
 * Returns all commodities with current rates
 */
export function getAllCommodityRates() {
  return COMMODITY_ONLINE_DATA.map((c) => ({
    id: c.id,
    name: c.name,
    slug: c.slug,
    category: c.category,
    sourceUrl: c.sourceUrl,
    sourceAttribution: c.sourceAttribution,
    market: c.primaryMarket,
    state: c.primaryState,
    price: c.nationalModalPrice,
    pricePerKg: c.nationalPricePerKg,
    unit: c.unit,
    minPrice: Math.min(...c.mandis.map((m) => m.minPrice)),
    maxPrice: Math.max(...c.mandis.map((m) => m.maxPrice)),
    change: c.change,
    trend: c.trend,
    volume: c.volume,
    grade: c.grade,
    mandis: c.mandis,
    marketSummary: c.marketSummary,
    lastUpdated: c.lastUpdated,
  }));
}
